//Celera Brick Generator Confidential
//CORE:oscillator
//NAME:oscillator_242d2a21
//GENERATOR REVISION:0.5.1
//TYPE:internal
//ACCURACY:yes%
//ENABLE:pin
//STANDBY:no
//SPREAD SPECTRUM:no
//FREQUENCY:1000KHz
//DUTY CYCLE:50%
//IREPLICA GAIN:0
//VMAX:6V
//DFT:no
//SS CONFIGURATION:fixed
//SS ENABLE CONTROL:fixed
//SS CLOCK SYNC:synchronized
//:SS CLOCK SOURCE50
//SS CLOCK DIVIDE:64
//SS RANGE POR:5
//SS MODE POR:sweep
//SS ENABLE POR:5

