//Celera Brick Generator Confidential
//CORE:vbias
//NAME:vbias_8430b59e
//GENERATOR REVISION:0.4.6
//NUMBER OF INPUTS:24
//MAX VIN1 VOLTAGE:40V
//UVLO:3V
//OUTPUT VOLTAGE:5V
//OUTPUT VOLTAGE ACCURACY:yes
//MAX OUTPUT CURRENT:20mA
//OUTPUT DISCHARGE:no
//ENABLE PIN:no
//OK FLAG:no
//DFT:yes

