// Celera Brick Generator Confidential
//CORE:resistorarray
//NAME:resistorarray_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
//GENERATOR CODE REVISION:0.3.2
//VALUE:25.00Kohms
//Imax:0.10000mA
//TYPE:poly
//VMAX:6V

//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10.v
//Celera:resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
//Celera Confidential Symbol Generator
//RESISTOR unit Value:25.00KOhm TYPE:2xpoly
module resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10 (RP,
CELG,
RN);
inout RP;
inout RN;
input CELG;
endmodule


//Celera Confidential Do Not Copy resistorarray_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
//Celera Confidential Symbol Generator
//RESISTOR unit Value:25.00KOhm TYPE:2xpoly
module resistorarray_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10 (RP1,
RP2,RN2,
CELG,
RN1);
inout RP1;
inout RN1;
inout RP2;
inout RN2;
input CELG;

//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10 XR1_0(
.RP (RP1),
.RN (RX1_0),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10 XR1_1(
.RP (RX1_0),
.RN (RX1_1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10 XR1_2(
.RP (RX1_1),
.RN (RX1_2),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10 XR1_3(
.RP (RX1_2),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10 XR2_0(
.RP (RP2),
.RN (RX2_0),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10 XR2_1(
.RP (RX2_0),
.RN (RX2_1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10 XR2_2(
.RP (RX2_1),
.RN (RX2_2),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10 XR2_3(
.RP (RX2_2),
.RN (RN2),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU10
//Celera Confidential Do Not Copy Module End
//Celera Schematic Generator
endmodule
