// Celera Brick Generator Confidential
//CORE:resistorarray
//NAME:resistorarray_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
//GENERATOR CODE REVISION:0.3.2
//VALUE:25.00Kohms
//Imax:0.10000mA
//TYPE:poly
//VMAX:6V

//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12.v
//Celera:resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Symbol Generator
//RESISTOR unit Value:25.00KOhm TYPE:1xpoly
module resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12 (RP,
CELG,
RN);
inout RP;
inout RN;
input CELG;
endmodule


//Celera Confidential Do Not Copy resistorarray_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Symbol Generator
//RESISTOR unit Value:25.00KOhm TYPE:1xpoly
module resistorarray_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12 (RP1,
CELG,
RN1);
inout RP1;
inout RN1;
input CELG;

//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12 XR1_0(
.RP (RP1),
.RN (RX1_0),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12 XR1_1(
.RP (RX1_0),
.RN (RX1_1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12 XR1_2(
.RP (RX1_1),
.RN (RX1_2),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12 XR1_3(
.RP (RX1_2),
.RN (RX1_3),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12 XR1_4(
.RP (RX1_3),
.RN (RX1_4),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12 XR1_5(
.RP (RX1_4),
.RN (RX1_5),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12 XR1_6(
.RP (RX1_5),
.RN (RX1_6),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12 XR1_7(
.RP (RX1_6),
.RN (RX1_7),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12 XR1_8(
.RP (RX1_7),
.RN (RX1_8),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12 XR1_9(
.RP (RX1_8),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVDDL_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy Module End
//Celera Schematic Generator
endmodule
