// Celera Brick Generator Confidential
//CORE:resistorarray
//NAME:resistorarray_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//GENERATOR CODE REVISION:0.3.2
//VALUE:30.00Kohms
//Imax:0.10000mA
//TYPE:poly
//VMAX:6V

//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10.v
//Celera:resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Symbol Generator
//RESISTOR unit Value:30.00KOhm TYPE:8xpoly
module resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 (RP,
CELG,
RN);
inout RP;
inout RN;
input CELG;
endmodule


//Celera Confidential Do Not Copy resistorarray_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Symbol Generator
//RESISTOR unit Value:30.00KOhm TYPE:8xpoly
module resistorarray_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 (RP1,
RP2,RN2,
RP3,RN3,
RP4,RN4,
RP5,RN5,
RP6,RN6,
RP7,RN7,
RP8,RN8,
CELG,
RN1);
inout RP1;
inout RN1;
inout RP2;
inout RN2;
inout RP3;
inout RN3;
inout RP4;
inout RN4;
inout RP5;
inout RN5;
inout RP6;
inout RN6;
inout RP7;
inout RN7;
inout RP8;
inout RN8;
input CELG;

//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR1_0(
.RP (RP1),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR1_1(
.RP (RP1),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR1_2(
.RP (RP1),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR1_3(
.RP (RP1),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR1_4(
.RP (RP1),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR1_5(
.RP (RP1),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR1_6(
.RP (RP1),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR1_7(
.RP (RP1),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR1_8(
.RP (RP1),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR1_9(
.RP (RP1),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR1_10(
.RP (RP1),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR1_11(
.RP (RP1),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR1_12(
.RP (RP1),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR1_13(
.RP (RP1),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR1_14(
.RP (RP1),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR1_15(
.RP (RP1),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR2_16(
.RP (RP2),
.RN (RN2),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR2_17(
.RP (RP2),
.RN (RN2),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR2_18(
.RP (RP2),
.RN (RN2),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR2_19(
.RP (RP2),
.RN (RN2),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR2_20(
.RP (RP2),
.RN (RN2),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR2_21(
.RP (RP2),
.RN (RN2),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR2_22(
.RP (RP2),
.RN (RN2),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR2_23(
.RP (RP2),
.RN (RN2),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR3_24(
.RP (RP3),
.RN (RN3),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR3_25(
.RP (RP3),
.RN (RN3),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR3_26(
.RP (RP3),
.RN (RN3),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR3_27(
.RP (RP3),
.RN (RN3),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR4_28(
.RP (RP4),
.RN (RN4),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR4_29(
.RP (RP4),
.RN (RN4),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR5_30(
.RP (RP5),
.RN (RN5),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR6_0(
.RP (RP6),
.RN (RX6_0),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR6_1(
.RP (RX6_0),
.RN (RN6),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR7_0(
.RP (RP7),
.RN (RX7_0),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR7_1(
.RP (RX7_0),
.RN (RX7_1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR7_2(
.RP (RX7_1),
.RN (RX7_2),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR7_3(
.RP (RX7_2),
.RN (RN7),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR8_0(
.RP (RP8),
.RN (RX8_0),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR8_1(
.RP (RX8_0),
.RN (RX8_1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR8_2(
.RP (RX8_1),
.RN (RX8_2),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR8_3(
.RP (RX8_2),
.RN (RX8_3),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR8_4(
.RP (RX8_3),
.RN (RX8_4),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR8_5(
.RP (RX8_4),
.RN (RX8_5),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR8_6(
.RP (RX8_5),
.RN (RX8_6),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10 XR8_7(
.RP (RX8_6),
.RN (RN8),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDR_XLOOP_XFEEDBACK_XU1_XU10
//Celera Confidential Do Not Copy Module End
//Celera Schematic Generator
endmodule
