// Celera Brick Generator Confidential
//CORE:resistorarray
//NAME:resistorarray_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//GENERATOR CODE REVISION:0.3.2
//VALUE:25.00Kohms
//Imax:0.10000mA
//TYPE:poly
//VMAX:6V

//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12.v
//Celera:resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Symbol Generator
//RESISTOR unit Value:25.00KOhm TYPE:2xpoly
module resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 (RP,
CELG,
RN);
inout RP;
inout RN;
input CELG;
endmodule


//Celera Confidential Do Not Copy resistorarray_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Symbol Generator
//RESISTOR unit Value:25.00KOhm TYPE:2xpoly
module resistorarray_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 (RP1,
RP2,RN2,
CELG,
RN1);
inout RP1;
inout RN1;
inout RP2;
inout RN2;
input CELG;

//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR1_0(
.RP (RP1),
.RN (RX1_0),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR1_1(
.RP (RX1_0),
.RN (RX1_1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR1_2(
.RP (RX1_1),
.RN (RX1_2),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR1_3(
.RP (RX1_2),
.RN (RX1_3),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR1_4(
.RP (RX1_3),
.RN (RX1_4),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR1_5(
.RP (RX1_4),
.RN (RX1_5),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR1_6(
.RP (RX1_5),
.RN (RX1_6),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR1_7(
.RP (RX1_6),
.RN (RN1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR2_0(
.RP (RP2),
.RN (RX2_0),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR2_1(
.RP (RX2_0),
.RN (RX2_1),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR2_2(
.RP (RX2_1),
.RN (RX2_2),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR2_3(
.RP (RX2_2),
.RN (RX2_3),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR2_4(
.RP (RX2_3),
.RN (RX2_4),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR2_5(
.RP (RX2_4),
.RN (RX2_5),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR2_6(
.RP (RX2_5),
.RN (RX2_6),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR2_7(
.RP (RX2_6),
.RN (RX2_7),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR2_8(
.RP (RX2_7),
.RN (RX2_8),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR2_9(
.RP (RX2_8),
.RN (RX2_9),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR2_10(
.RP (RX2_9),
.RN (RX2_10),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR2_11(
.RP (RX2_10),
.RN (RX2_11),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR2_12(
.RP (RX2_11),
.RN (RX2_12),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR2_13(
.RP (RX2_12),
.RN (RX2_13),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR2_14(
.RP (RX2_13),
.RN (RX2_14),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12 XR2_15(
.RP (RX2_14),
.RN (RN2),
.CELG (CELG)
);
//,diesize,resistorunit_XBOB_XDESIGN_XCOREVLEDGB_XLOOP_XFEEDBACK_XU1_XU12
//Celera Confidential Do Not Copy Module End
//Celera Schematic Generator
endmodule
