// ------------------------ Module Definitions -----------
module BOBCATvddrLOOPate_XBOB_XDESIGN_XCOREVDDR_XLOOP_XATE (go,tdo,tmi,clock,enable,CELG59462,CELV96848,go_driver,CELSUB40948,clock_driver,enable_driver);
  output  go;
  inout  tdo;
  input [4:0] tmi;
  output  clock;
  output  enable;
  input  CELG59462;
  input  CELV96848;
  input  go_driver;
  input  CELSUB40948;
  input  clock_driver;
  input  enable_driver;
endmodule

module STEPDOWNalgorithmCONTROL3p1_PYES_XBOB_XDESIGN_XCOREVDDR_XLOOP_XCONTROL (tdo,tmi,porb,clock,topstate,CELG59462,CELV96848,go_driver,ok_driver,topswipeak,CELSUB40948,fault_control,enable_control,freeze_control,switch_control);
  inout  tdo;
  input [4:0] tmi;
  input  porb;
  input  clock;
  output  topstate;
  input  CELG59462;
  input  CELV96848;
  input  go_driver;
  input  ok_driver;
  input  topswipeak;
  input  CELSUB40948;
  output  fault_control;
  input  enable_control;
  input  freeze_control;
  input  switch_control;
endmodule

module BOBCATvddrDRIVER_XBOB_XDESIGN_XCOREVDDR_XLOOP_XDRIVER (SW,tdo,tmi,MUDV,PMUDG,PMUDV,TAEXT,topstate,CELG59462,CELV96848,ok_driver,topswipeak,CELSUB40948,IREF_DRIVER,enable_driver);
  inout  SW;
  inout  tdo;
  input [4:0] tmi;
  input  MUDV;
  input  PMUDG;
  inout  PMUDV;
  input  TAEXT;
  input  topstate;
  input  CELG59462;
  input  CELV96848;
  output  ok_driver;
  output  topswipeak;
  input  CELSUB40948;
  input  IREF_DRIVER;
  input  enable_driver;
endmodule

module BOBCATvddrFEEDBACK_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK (FBI,TAO,tdo,tmi,MUDV,CELG59462,CELV96848,sense_OUT,CELSUB40948,kelvin_MUDG,ok_feedback,FB_REFERENCE,REF_FEEDBACK,enable_feedback,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU2,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU8,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU16,register_VDDRoutput_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU5);
  inout  FBI;
  inout  TAO;
  inout  tdo;
  input [4:0] tmi;
  input  MUDV;
  input  CELG59462;
  input  CELV96848;
  inout  sense_OUT;
  input  CELSUB40948;
  inout  kelvin_MUDG;
  output  ok_feedback;
  inout  FB_REFERENCE;
  input  REF_FEEDBACK;
  input  enable_feedback;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU2;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU8;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU16;
  input [7:0] register_VDDRoutput_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU5;
endmodule

module BOBCATvddrREGULATION_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION (TAO,tdo,tmi,MUDV,TAEXT,REF_LOOP,CELG59462,CELV96848,go_driver,CELREF84329,CELSUB40948,IREF_DRIVER,kelvin_MUDG,FB_REGULATION,ok_regulation,REF_REGULATION,VSS_REGULATION,IREF_REGULATION,clock_regulation,enable_regulation,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU1,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU3,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU7,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU9,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU12,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU15,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU36);
  inout  TAO;
  inout  tdo;
  inout [4:0] tmi;
  input  MUDV;
  input  TAEXT;
  input  REF_LOOP;
  input  CELG59462;
  input  CELV96848;
  output  go_driver;
  input  CELREF84329;
  input  CELSUB40948;
  inout  IREF_DRIVER;
  inout  kelvin_MUDG;
  inout  FB_REGULATION;
  output  ok_regulation;
  output  REF_REGULATION;
  input  VSS_REGULATION;
  inout  IREF_REGULATION;
  input  clock_regulation;
  input  enable_regulation;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU1;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU3;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU7;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU9;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU12;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU15;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU36;
endmodule

// ------------------------ Module Verilog ---------------
module BOBCATvddrLOOP_XBOB_XDESIGN_XCOREVDDR_XLOOP (SW, TAO, tdo, tmi, MUDV, porb, PMUDG, PMUDV, TAEXT, FB_LOOP, REF_LOOP, CELG59462, CELV96848, ok_driver, sense_OUT, fault_loop, CELREF84329, CELSUB40948, kelvin_MUDG, ok_feedback, FB_REFERENCE, clock_driver, fault_freeze, ilimit_fault, enable_driver, ok_regulation, REF_REGULATION, VSS_REGULATION, switch_control, IREF_REGULATION, enable_feedback, enable_regulation, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU1, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU3, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU7, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU9, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU2, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU8, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU12, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU15, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU36, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU16, register_VDDRoutput_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU5);
inout  SW;
inout  TAO;
inout  tdo;
input [4:0] tmi;
input  MUDV;
input  porb;
input  PMUDG;
inout  PMUDV;
input  TAEXT;
inout  FB_LOOP;
input  REF_LOOP;
input  CELG59462;
input  CELV96848;
output  ok_driver;
inout  sense_OUT;
output  fault_loop;
input  CELREF84329;
input  CELSUB40948;
inout  kelvin_MUDG;
output  ok_feedback;
inout  FB_REFERENCE;
input  clock_driver;
input  fault_freeze;
output  ilimit_fault;
input  enable_driver;
output  ok_regulation;
output  REF_REGULATION;
input  VSS_REGULATION;
input  switch_control;
inout  IREF_REGULATION;
input  enable_feedback;
input  enable_regulation;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU1;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU3;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU7;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU9;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU2;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU8;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU12;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU15;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU36;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU16;
input [7:0] register_VDDRoutput_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU5;


// ------------------------ Wires ------------------------
wire [4:0] tmi;
wire [7:0] register_VDDRoutput_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU5;

// ------------------------ Networks ---------------------
BOBCATvddrLOOPate_XBOB_XDESIGN_XCOREVDDR_XLOOP_XATE XATE (
.go(net_103),
.tdo(tdo),
.tmi(tmi[4:0]),
.clock(net_105),
.enable(net_99),
.CELG59462(CELG59462),
.CELV96848(CELV96848),
.go_driver(net_102),
.CELSUB40948(CELSUB40948),
.clock_driver(clock_driver),
.enable_driver(enable_driver)
);

STEPDOWNalgorithmCONTROL3p1_PYES_XBOB_XDESIGN_XCOREVDDR_XLOOP_XCONTROL XCONTROL (
.tdo(tdo),
.tmi(tmi[4:0]),
.porb(porb),
.clock(net_105),
.topstate(net_123),
.CELG59462(CELG59462),
.CELV96848(CELV96848),
.go_driver(net_103),
.ok_driver(ok_driver),
.topswipeak(ilimit_fault),
.CELSUB40948(CELSUB40948),
.fault_control(fault_loop),
.enable_control(net_99),
.freeze_control(fault_freeze),
.switch_control(switch_control)
);

BOBCATvddrDRIVER_XBOB_XDESIGN_XCOREVDDR_XLOOP_XDRIVER XDRIVER (
.SW(SW),
.tdo(tdo),
.tmi(tmi[4:0]),
.MUDV(MUDV),
.PMUDG(PMUDG),
.PMUDV(PMUDV),
.TAEXT(TAEXT),
.topstate(net_123),
.CELG59462(CELG59462),
.CELV96848(CELV96848),
.ok_driver(ok_driver),
.topswipeak(ilimit_fault),
.CELSUB40948(CELSUB40948),
.IREF_DRIVER(net_110),
.enable_driver(net_99)
);

BOBCATvddrFEEDBACK_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK XFEEDBACK (
.FBI(FB_LOOP),
.TAO(TAO),
.tdo(tdo),
.tmi(tmi[4:0]),
.MUDV(MUDV),
.CELG59462(CELG59462),
.CELV96848(CELV96848),
.sense_OUT(sense_OUT),
.CELSUB40948(CELSUB40948),
.kelvin_MUDG(kelvin_MUDG),
.ok_feedback(ok_feedback),
.FB_REFERENCE(FB_REFERENCE),
.REF_FEEDBACK(REF_LOOP),
.enable_feedback(enable_feedback),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU2(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU2),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU8(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU8),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU16(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU16),
.register_VDDRoutput_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU5(register_VDDRoutput_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU5[7:0])
);

BOBCATvddrREGULATION_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION XREGULATION (
.TAO(TAO),
.tdo(tdo),
.tmi(tmi[4:0]),
.MUDV(MUDV),
.TAEXT(TAEXT),
.REF_LOOP(REF_LOOP),
.CELG59462(CELG59462),
.CELV96848(CELV96848),
.go_driver(net_102),
.CELREF84329(CELREF84329),
.CELSUB40948(CELSUB40948),
.IREF_DRIVER(net_110),
.kelvin_MUDG(kelvin_MUDG),
.FB_REGULATION(FB_LOOP),
.ok_regulation(ok_regulation),
.REF_REGULATION(REF_REGULATION),
.VSS_REGULATION(VSS_REGULATION),
.IREF_REGULATION(IREF_REGULATION),
.clock_regulation(net_105),
.enable_regulation(enable_regulation),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU1(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU1),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU3(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU3),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU7(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU7),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU9(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU9),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU12(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU12),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU15(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU15),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU36(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU36)
);

endmodule

