// ------------------------ Module Definitions -----------
module BOBCATvddrREGULATIONcontrol_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11 (VC,TAO,tdo,tmi,MUDV,TAEXT,ISLOPE,REF_LOOP,CELG59462,CELV96848,go_driver,CELREF84329,CELSUB40948,IREF_DRIVER,kelvin_MUDG,FB_REGULATION,ok_regulation,REF_REGULATION,VSS_REGULATION,IREF_REGULATION,clock_regulation,enable_regulation,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU1,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU3,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU7,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU9,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU12,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU15,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU36);
  inout  VC;
  inout  TAO;
  inout  tdo;
  inout [4:0] tmi;
  input  MUDV;
  input  TAEXT;
  inout  ISLOPE;
  input  REF_LOOP;
  input  CELG59462;
  input  CELV96848;
  output  go_driver;
  input  CELREF84329;
  input  CELSUB40948;
  inout  IREF_DRIVER;
  inout  kelvin_MUDG;
  input  FB_REGULATION;
  output  ok_regulation;
  output  REF_REGULATION;
  input  VSS_REGULATION;
  inout  IREF_REGULATION;
  input  clock_regulation;
  input  enable_regulation;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU1;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU3;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU7;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU9;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU12;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU15;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU36;
endmodule

module BOBCATvddrREGULATIONate_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU2 (VC,TAO,tdo,tmi,clock,ISLOPE,enable,CELG59462,CELV96848,go_driver,CELSUB40948,IREF_DRIVER,FB_REGULATION,ok_regulation,REF_REGULATION,clock_regulation,enable_regulation);
  input  VC;
  inout  TAO;
  inout  tdo;
  inout [4:0] tmi;
  output  clock;
  input  ISLOPE;
  output  enable;
  input  CELG59462;
  input  CELV96848;
  input  go_driver;
  input  CELSUB40948;
  input  IREF_DRIVER;
  inout  FB_REGULATION;
  input  ok_regulation;
  input  REF_REGULATION;
  input  clock_regulation;
  input  enable_regulation;
endmodule

// ------------------------ Module Verilog ---------------
module BOBCATvddrREGULATION_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION (TAO, tdo, tmi, MUDV, TAEXT, REF_LOOP, CELG59462, CELV96848, go_driver, CELREF84329, CELSUB40948, IREF_DRIVER, kelvin_MUDG, FB_REGULATION, ok_regulation, REF_REGULATION, VSS_REGULATION, IREF_REGULATION, clock_regulation, enable_regulation, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU1, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU3, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU7, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU9, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU12, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU15, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU36);
inout  TAO;
inout  tdo;
inout [4:0] tmi;
input  MUDV;
input  TAEXT;
input  REF_LOOP;
input  CELG59462;
input  CELV96848;
output  go_driver;
input  CELREF84329;
input  CELSUB40948;
inout  IREF_DRIVER;
inout  kelvin_MUDG;
inout  FB_REGULATION;
output  ok_regulation;
output  REF_REGULATION;
input  VSS_REGULATION;
inout  IREF_REGULATION;
input  clock_regulation;
input  enable_regulation;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU1;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU3;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU7;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU9;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU12;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU15;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU36;


// ------------------------ Wires ------------------------
wire [4:0] tmi;

// ------------------------ Networks ---------------------
BOBCATvddrREGULATIONcontrol_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11 XU11 (
.VC(net_65),
.TAO(TAO),
.tdo(tdo),
.tmi(tmi[4:0]),
.MUDV(MUDV),
.TAEXT(TAEXT),
.ISLOPE(net_63),
.REF_LOOP(REF_LOOP),
.CELG59462(CELG59462),
.CELV96848(CELV96848),
.go_driver(go_driver),
.CELREF84329(CELREF84329),
.CELSUB40948(CELSUB40948),
.IREF_DRIVER(IREF_DRIVER),
.kelvin_MUDG(kelvin_MUDG),
.FB_REGULATION(FB_REGULATION),
.ok_regulation(ok_regulation),
.REF_REGULATION(REF_REGULATION),
.VSS_REGULATION(VSS_REGULATION),
.IREF_REGULATION(IREF_REGULATION),
.clock_regulation(net_62),
.enable_regulation(net_61),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU1(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU1),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU3(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU3),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU7(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU7),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU9(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU9),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU12(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU12),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU15(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU15),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU36(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU11_XU36)
);

BOBCATvddrREGULATIONate_XBOB_XDESIGN_XCOREVDDR_XLOOP_XREGULATION_XU2 XU2 (
.VC(net_65),
.TAO(TAO),
.tdo(tdo),
.tmi(tmi[4:0]),
.clock(net_62),
.ISLOPE(net_63),
.enable(net_61),
.CELG59462(CELG59462),
.CELV96848(CELV96848),
.go_driver(go_driver),
.CELSUB40948(CELSUB40948),
.IREF_DRIVER(IREF_DRIVER),
.FB_REGULATION(FB_REGULATION),
.ok_regulation(ok_regulation),
.REF_REGULATION(REF_REGULATION),
.clock_regulation(clock_regulation),
.enable_regulation(enable_regulation)
);

endmodule

