// ------------------------ Module Definitions -----------
module BOBCATvddrFEEDBACKate_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XATE (FBI,TAO,tdo,tmi,enable,CELG59462,CELV96848,CELSUB40948,ok_feedback,FB_REFERENCE,enable_feedback);
  input  FBI;
  inout  TAO;
  inout  tdo;
  input [4:0] tmi;
  output  enable;
  input  CELG59462;
  input  CELV96848;
  input  CELSUB40948;
  input  ok_feedback;
  input  FB_REFERENCE;
  input  enable_feedback;
endmodule

module BOBCATvddrFEEDBACKselect_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT (FBI,tmi,MUDV,CELG59462,CELV96848,sense_OUT,CELSUB40948,kelvin_MUDG,ok_feedback,FB_REFERENCE,REF_FEEDBACK,enable_feedback,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU2,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU8,IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU16,register_VDDRoutput_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU5);
  inout  FBI;
  inout [4:0] tmi;
  input  MUDV;
  input  CELG59462;
  input  CELV96848;
  inout  sense_OUT;
  input  CELSUB40948;
  inout  kelvin_MUDG;
  output  ok_feedback;
  inout  FB_REFERENCE;
  input  REF_FEEDBACK;
  input  enable_feedback;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU2;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU8;
  input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU16;
  input [7:0] register_VDDRoutput_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU5;
endmodule

// ------------------------ Module Verilog ---------------
module BOBCATvddrFEEDBACK_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK (FBI, TAO, tdo, tmi, MUDV, CELG59462, CELV96848, sense_OUT, CELSUB40948, kelvin_MUDG, ok_feedback, FB_REFERENCE, REF_FEEDBACK, enable_feedback, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU2, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU8, IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU16, register_VDDRoutput_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU5);
inout  FBI;
inout  TAO;
inout  tdo;
input [4:0] tmi;
input  MUDV;
input  CELG59462;
input  CELV96848;
inout  sense_OUT;
input  CELSUB40948;
inout  kelvin_MUDG;
output  ok_feedback;
inout  FB_REFERENCE;
input  REF_FEEDBACK;
input  enable_feedback;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU2;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU8;
input  IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU16;
input [7:0] register_VDDRoutput_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU5;


// ------------------------ Wires ------------------------
wire [4:0] tmi;
wire [7:0] register_VDDRoutput_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU5;

// ------------------------ Networks ---------------------
BOBCATvddrFEEDBACKate_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XATE XATE (
.FBI(FBI),
.TAO(TAO),
.tdo(tdo),
.tmi(tmi[4:0]),
.enable(net_38),
.CELG59462(CELG59462),
.CELV96848(CELV96848),
.CELSUB40948(CELSUB40948),
.ok_feedback(ok_feedback),
.FB_REFERENCE(FB_REFERENCE),
.enable_feedback(enable_feedback)
);

BOBCATvddrFEEDBACKselect_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT XSELECT (
.FBI(FBI),
.tmi(tmi[4:0]),
.MUDV(MUDV),
.CELG59462(CELG59462),
.CELV96848(CELV96848),
.sense_OUT(sense_OUT),
.CELSUB40948(CELSUB40948),
.kelvin_MUDG(kelvin_MUDG),
.ok_feedback(ok_feedback),
.FB_REFERENCE(FB_REFERENCE),
.REF_FEEDBACK(REF_FEEDBACK),
.enable_feedback(net_38),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU2(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU2),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU8(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU8),
.IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU16(IP_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU16),
.register_VDDRoutput_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU5(register_VDDRoutput_XBOB_XDESIGN_XCOREVDDR_XLOOP_XFEEDBACK_XSELECT_XU5[7:0])
);

endmodule

