// ------------------------ Module Definitions -----------
//Verilog HDL for "Generate", "STONEpad1" "functional"


module STONEpad1 ( PAD );

  inout PAD;
endmodule


//Verilog HDL for "Generate", "STONEotpSENSE" "functional"


module STONEotpSENSE ( PAD, OTP );

  input PAD;
  output OTP;
endmodule


//Verilog HDL for "Generate", "WRAPPER1" "functional"


module WRAPPER1 ( o, i );

  input i;
  output o;
endmodule


// ------------------------ Module Verilog ---------------
module pad_BOBCAT_GND (GND, GESD, GOTP, CELG59462, CELSUB40948, kelvin_LEDR, kelvin_MUDG, kelvin_VDDL, kelvin_VDDR, kelvin_VLDO, kelvin_LEDGB, SENSE_G_IBIAS, celkelvin_CELG, senseCELG38473, SENSE_G_XBOB_XTELEMETRY_XAQUIRE_XU6, SENSE_G_XBOB_XSERVICE_XOSCILLATOR_XU1, SENSE_G_XBOB_XSERVICE_XOSCILLATOR_XU12, SENSE_G_XBOB_XDESIGN_XCOREVDDL_XSOFTSTART_XU9_XU1, SENSE_G_XBOB_XDESIGN_XCOREVDDR_XSOFTSTART_XU8_XU8, SENSE_G_XBOB_XDESIGN_XCOREVLEDR_XSOFTSTART_XU9_XU1, SENSE_G_XBOB_XDESIGN_XCOREVLEDGB_XSOFTSTART_XU9_XU1);
inout  GND;
output  GESD;
output  GOTP;
output  CELG59462;
output  CELSUB40948;
inout  kelvin_LEDR;
inout  kelvin_MUDG;
inout  kelvin_VDDL;
inout  kelvin_VDDR;
inout  kelvin_VLDO;
inout  kelvin_LEDGB;
output  SENSE_G_IBIAS;
output  celkelvin_CELG;
output  senseCELG38473;
output  SENSE_G_XBOB_XTELEMETRY_XAQUIRE_XU6;
output  SENSE_G_XBOB_XSERVICE_XOSCILLATOR_XU1;
output  SENSE_G_XBOB_XSERVICE_XOSCILLATOR_XU12;
output  SENSE_G_XBOB_XDESIGN_XCOREVDDL_XSOFTSTART_XU9_XU1;
output  SENSE_G_XBOB_XDESIGN_XCOREVDDR_XSOFTSTART_XU8_XU8;
output  SENSE_G_XBOB_XDESIGN_XCOREVLEDR_XSOFTSTART_XU9_XU1;
output  SENSE_G_XBOB_XDESIGN_XCOREVLEDGB_XSOFTSTART_XU9_XU1;


// ------------------------ Wires ------------------------

// ------------------------ Networks ---------------------
STONEpad1 XPAD1 (
.PAD(GND)
);

STONEotpSENSE Xgotp (
.OTP(GOTP),
.PAD(GND)
);

WRAPPER1 Xwrap_CELG (
.i(GND),
.o(CELG59462)
);

WRAPPER1 Xwrap_GESD (
.i(GND),
.o(GESD)
);

WRAPPER1 Xwrap_CELSUB (
.i(GND),
.o(CELSUB40948)
);

WRAPPER1 Xwrap_PAD1_SENSE0 (
.i(GND),
.o(kelvin_VDDR)
);

WRAPPER1 Xwrap_PAD1_SENSE1 (
.i(GND),
.o(kelvin_VDDL)
);

WRAPPER1 Xwrap_PAD1_SENSE2 (
.i(GND),
.o(kelvin_LEDGB)
);

WRAPPER1 Xwrap_PAD1_SENSE3 (
.i(GND),
.o(kelvin_LEDR)
);

WRAPPER1 Xwrap_PAD1_SENSE4 (
.i(GND),
.o(kelvin_VLDO)
);

WRAPPER1 Xwrap_PAD1_SENSE5 (
.i(GND),
.o(kelvin_MUDG)
);

WRAPPER1 XWRAP_SENSE_G_IBIAS (
.i(GND),
.o(SENSE_G_IBIAS)
);

WRAPPER1 XWRAP_celkelvin_CELG (
.i(GND),
.o(celkelvin_CELG)
);

WRAPPER1 XWRAP_senseCELG38473 (
.i(GND),
.o(senseCELG38473)
);

WRAPPER1 XWRAP_SENSE_G_XBOB_XTELEMETRY_XAQUIRE_XU6 (
.i(GND),
.o(SENSE_G_XBOB_XTELEMETRY_XAQUIRE_XU6)
);

WRAPPER1 XWRAP_SENSE_G_XBOB_XSERVICE_XOSCILLATOR_XU1 (
.i(GND),
.o(SENSE_G_XBOB_XSERVICE_XOSCILLATOR_XU1)
);

WRAPPER1 XWRAP_SENSE_G_XBOB_XSERVICE_XOSCILLATOR_XU12 (
.i(GND),
.o(SENSE_G_XBOB_XSERVICE_XOSCILLATOR_XU12)
);

WRAPPER1 XWRAP_SENSE_G_XBOB_XDESIGN_XCOREVDDL_XSOFTSTART_XU9_XU1 (
.i(GND),
.o(SENSE_G_XBOB_XDESIGN_XCOREVDDL_XSOFTSTART_XU9_XU1)
);

WRAPPER1 XWRAP_SENSE_G_XBOB_XDESIGN_XCOREVDDR_XSOFTSTART_XU8_XU8 (
.i(GND),
.o(SENSE_G_XBOB_XDESIGN_XCOREVDDR_XSOFTSTART_XU8_XU8)
);

WRAPPER1 XWRAP_SENSE_G_XBOB_XDESIGN_XCOREVLEDR_XSOFTSTART_XU9_XU1 (
.i(GND),
.o(SENSE_G_XBOB_XDESIGN_XCOREVLEDR_XSOFTSTART_XU9_XU1)
);

WRAPPER1 XWRAP_SENSE_G_XBOB_XDESIGN_XCOREVLEDGB_XSOFTSTART_XU9_XU1 (
.i(GND),
.o(SENSE_G_XBOB_XDESIGN_XCOREVLEDGB_XSOFTSTART_XU9_XU1)
);

endmodule

