module dftprobe_XBOB_XDESIGN_XCOREVLEDR_XCONVERTER_XU70 (i,tdi_CONVERTERcoreDPSGRD_Rev3_SOFTSTART,ten_CONVERTERcoreDPSGRD_Rev3_SOFTSTART,CELG,CELSUB,CELV);
input  i;
output  tdi_CONVERTERcoreDPSGRD_Rev3_SOFTSTART;
input  ten_CONVERTERcoreDPSGRD_Rev3_SOFTSTART;
input  CELG;
input  CELSUB;
input  CELV;
endmodule

