module dftprobe_XBOB_XDESIGN_XCOREVDDL_XCORE_XU64 (i,tdi_CONVERTERcoreDPSGRD_Rev3_DISCHARGE,ten_CONVERTERcoreDPSGRD_Rev3_DISCHARGE,CELG,CELSUB,CELV);
input  i;
output  tdi_CONVERTERcoreDPSGRD_Rev3_DISCHARGE;
input  ten_CONVERTERcoreDPSGRD_Rev3_DISCHARGE;
input  CELG;
input  CELSUB;
input  CELV;
endmodule

