module dftprobe_XBOB_XDESIGN_XCOREVLEDR_XCONVERTER_XU67 (i,tdi_CONVERTERcoreDPSGRD_Rev3_UNDEF4,ten_CONVERTERcoreDPSGRD_Rev3_UNDEF4,CELG,CELSUB,CELV);
input  i;
output  tdi_CONVERTERcoreDPSGRD_Rev3_UNDEF4;
input  ten_CONVERTERcoreDPSGRD_Rev3_UNDEF4;
input  CELG;
input  CELSUB;
input  CELV;
endmodule

